Add/fix internal linting
Tibfib/eslint-plugin-import-helpers pull request #45
Opened 2022-01-07 16:35 UTC by bmish

Fixes a bunch of issues:

* Add `lint` script to run internal linting
* Add linting config with eslint / eslint-plugin-eslint-plugin / eslint-plugin-node / prettier
  * These are the plugins recommended by: https://eslint.org/docs/developer-guide/working-with-plugins#linting
  * Uses existing prettier configuration in .prettierrc
* Autofixed lint violations
* Fixed some inconsistencies with TypeScript usage
* Add npm keywords to package.json recommended by: https://eslint.org/docs/developer-guide/working-with-plugins#share-plugins

It looks like test/linting aren't running on CI, so separately GitHub Actions should be added to run those.

2022-01-07 16:37 UTC, bmish commented on .eslintignore
> +lib/
Don't lint compiled JS files.

2022-01-07 16:37 UTC, bmish commented on src/index.ts
> +export = {
Converts this file to TS like every other file in `src/`.

2022-01-07 16:37 UTC, bmish commented on src/rules/order-imports.ts
> +export default {
`export default` should be used in TypeScript.

2022-01-07 16:37 UTC, bmish commented on src/rules/order-imports.ts
> +					context.report({ node, message: error.message });
Fixes violation of: https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/blob/main/docs/rules/no-deprecated-report-api.md

2022-01-07 16:37 UTC, bmish commented on src/util/import-type.ts
> +const moduleRegExp = /^[^/\\.]/;
https://eslint.org/docs/rules/no-useless-escape

2022-01-30 16:54 UTC, ddzz requested changes

2022-01-30 16:54 UTC, ddzz commented on package.json
> +		"lint:js": "eslint .",
```suggestion
		"lint:js": "eslint --cache .",
```

2022-01-30 17:40 UTC, ddzz approved these changes

2022-04-14 16:34 UTC, merged

2022-04-14 16:34 UTC, Tibfib commented
LGTM! Thank you!